### ISSUE TITLE
求数据集

### ISSUE THREAD

**Issue by uzumakina** [zsz147/MineHunter#1]
学长，请问能否提供数据集呢，个人学习所用，谢谢。邮箱157914837@qq.com

**Comment by zsz147** [comment]
同学你好，数据集目前已经整理完成，并放到我们的研究室的数据发布平台中（http://de.nm.cernet.edu.cn/  （IPv6 only）），但是由于数据量庞大（总量约2TB），因此没有开放全部的下载权限。同学如果你确有需要，请给我们发邮件讲清楚你的用途，以及个人相关信息，以便我们确认能否提供相关的数据。请将邮件发送到我的邮箱zsz16@mails.tsinghua.edu.cn。并抄送给研究室的张老师hzhang@cernet.edu.cn。
